// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7SjQz_GG338jTm3Uxdxjq0ZgeRgOmy8',
    appId: '1:619825057353:web:0fe815dbe8991a5aa7b998',
    messagingSenderId: '619825057353',
    projectId: 'fork-app-2200b',
    authDomain: 'fork-app-2200b.firebaseapp.com',
    storageBucket: 'fork-app-2200b.firebasestorage.app',
    measurementId: 'G-R9678WSNGT',
    databaseURL:
        'https://fork-app-2200b-default-rtdb.firebaseio.com', // <<< هنا كمان
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk-vmbwWcQsE_4zojA8JIkFluOHa3H4Ro',
    appId: '1:619825057353:android:e1c0ec2f3d36e37ea7b998',
    messagingSenderId: '619825057353',
    projectId: 'fork-app-2200b',
    storageBucket: 'fork-app-2200b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf0MP6XyfbuykRG7DtuKTtmsNthJikGY4',
    appId: '1:619825057353:ios:3013f8424fb11a5ba7b998',
    messagingSenderId: '619825057353',
    projectId: 'fork-app-2200b',
    storageBucket: 'fork-app-2200b.firebasestorage.app',
    iosBundleId: 'com.example.responsive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf0MP6XyfbuykRG7DtuKTtmsNthJikGY4',
    appId: '1:619825057353:ios:3013f8424fb11a5ba7b998',
    messagingSenderId: '619825057353',
    projectId: 'fork-app-2200b',
    storageBucket: 'fork-app-2200b.firebasestorage.app',
    iosBundleId: 'com.example.responsive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs7SjQz_GG338jTm3Uxdxjq0ZgeRgOmy8',
    appId: '1:619825057353:web:6748e244318b2ec9a7b998',
    messagingSenderId: '619825057353',
    projectId: 'fork-app-2200b',
    authDomain: 'fork-app-2200b.firebaseapp.com',
    storageBucket: 'fork-app-2200b.firebasestorage.app',
    measurementId: 'G-1WGJ818KGG',
  );
}
